name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --prod --base-href /SSNS/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/SSNS/